# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allChildrenCPP <- function(E) {
    .Call('_rscistree_allChildrenCPP', PACKAGE = 'rscistree', E)
}

reorder_rows <- function(x, y) {
    .Call('_rscistree_reorder_rows', PACKAGE = 'rscistree', x, y)
}

reorderRcpp <- function(E) {
    .Call('_rscistree_reorderRcpp', PACKAGE = 'rscistree', E)
}

nnin_cpp <- function(E, n) {
    .Call('_rscistree_nnin_cpp', PACKAGE = 'rscistree', E, n)
}

CgetQ <- function(logQ, children_dict, node_order) {
    .Call('_rscistree_CgetQ', PACKAGE = 'rscistree', logQ, children_dict, node_order)
}

score_tree_cpp <- function(E, P) {
    .Call('_rscistree_score_tree_cpp', PACKAGE = 'rscistree', E, P)
}

nni_cpp_parallel <- function(tree, P) {
    .Call('_rscistree_nni_cpp_parallel', PACKAGE = 'rscistree', tree, P)
}

