# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allChildrenCPP <- function(E) {
    .Call('_scistreer_allChildrenCPP', PACKAGE = 'scistreer', E)
}

reorder_rows <- function(x, y) {
    .Call('_scistreer_reorder_rows', PACKAGE = 'scistreer', x, y)
}

reorderRcpp <- function(E) {
    .Call('_scistreer_reorderRcpp', PACKAGE = 'scistreer', E)
}

nnin_cpp <- function(E, n) {
    .Call('_scistreer_nnin_cpp', PACKAGE = 'scistreer', E, n)
}

nnin_score <- function(E, n, logQ, L_0) {
    .Call('_scistreer_nnin_score', PACKAGE = 'scistreer', E, n, logQ, L_0)
}

CgetQ <- function(logQ, children_dict, node_order) {
    .Call('_scistreer_CgetQ', PACKAGE = 'scistreer', logQ, children_dict, node_order)
}

get_logQ <- function(E, P) {
    .Call('_scistreer_get_logQ', PACKAGE = 'scistreer', E, P)
}

score_tree_cpp <- function(E, P) {
    .Call('_scistreer_score_tree_cpp', PACKAGE = 'scistreer', E, P)
}

get_score <- function(logQ, P) {
    .Call('_scistreer_get_score', PACKAGE = 'scistreer', logQ, P)
}

nni_cpp_parallel_new <- function(tree, P) {
    .Call('_scistreer_nni_cpp_parallel_new', PACKAGE = 'scistreer', tree, P)
}

nni_cpp_parallel <- function(tree, P) {
    .Call('_scistreer_nni_cpp_parallel', PACKAGE = 'scistreer', tree, P)
}

